<?php

declare(strict_types=1);
defined('ABSPATH') || exit;

require_once get_template_directory() . '/includes/theme-settings.php';


//=================================
// THEME SETUP
//=================================
//
add_action('after_setup_theme', 'sartorello_woo_theme_setup');

function sartorello_woo_theme_setup(): void
{
    // Theme Supports
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('automatic-feed-links');
    add_theme_support('custom-logo', [
        'height'      => 80,
        'width'       => 240,
        'flex-height' => true,
        'flex-width'  => true,
        'header-text' => ['site-title', 'site-description']
    ]);

    // WooCommerce Support
    add_theme_support('woocommerce');
    // add_theme_support('wc-product-gallery-zoom');
    // add_theme_support('wc-product-gallery-lightbox');
    // add_theme_support('wc-product-gallery-slider');

    // Register Nav Menus
    register_nav_menus([
        'sartorello-woo-theme_furniture'  => __('Furniture Menu', 'sartorello-woo-theme'),
        'sartorello-woo-theme_decoration' => __('Decoration Menu', 'sartorello-woo-theme'),
        'sartorello-woo-theme_lighting'   => __('Lighting Menu', 'sartorello-woo-theme'),
    ]);
}


//==========================================
// WooCommerce Integration & Improvements
//==========================================
//
// Remove WooCommerce styles.
// This prevent default WooCommerce styles from overriding our own.
add_filter('woocommerce_enqueue_styles', '__return_false');

// Remove Page Title from WooCommerce pages.
add_filter('woocommerce_show_page_title', '__return_false');


//========================================
// Enqueue custom scripts and styles
//========================================
//
add_action('wp_enqueue_scripts', 'enqueue_styles_and_scripts');

function enqueue_styles_and_scripts(): void
{
    // Global Theme CSS (generated by Tailwind CSS)
    wp_enqueue_style('global-theme-styles', get_template_directory_uri() . '/assets/frontend/css/style.css');
    // Main JavaScript Bundle
    wp_enqueue_script('main-theme-js', get_template_directory_uri() . '/assets/frontend/js/bundle.js', [], null, true);

    // Enqueue scripts for single product pages
    if (is_product()) {
        // Resize Thumbnails Script
        wp_enqueue_script('resize-thumbnails', get_template_directory_uri() . '/assets/frontend/js/resize-thumbnails.js', [], null, true);
    }
}


/**
 * Change the parameters for the "Related Products" section in single product pages 
 */
add_filter('woocommerce_output_related_products_args', 'change_related_products_args');

function change_related_products_args($args)
{
    $args['posts_per_page'] = 12;

    return $args;
}


/**
 * Add WhatApp contact button to WooCommerce single product pages
 */
add_action('woocommerce_after_add_to_cart_button', 'add_whatsapp_button_to_product_page', 1);

function add_whatsapp_button_to_product_page()
{
    wc_get_template('single-product/whatsapp-button.php');
}


/**
 * Add title to the shipping calculator on the single product page.
 */
add_action('csbmw_before_shipping_calculator', 'add_title_to_the_shipping_calculator');

function add_title_to_the_shipping_calculator() {
    ob_start();
    ?>

    <h3 class="mt-6 -mb-4 text-xs font-semibold tracking-wider">SIMULAR FRETE E PRAZO DE ENTREGA</h3>

    <?php
    echo wp_kses_post(ob_get_clean());
}

/**
 * Add Tailwind CSS classes to WooCommerce cart item thumbnail images
 */
add_filter('woocommerce_cart_item_thumbnail', 'add_tailwind_classes_to_cart_item_thumbnail', 10, 3);

function add_tailwind_classes_to_cart_item_thumbnail($thumbnail, $cart_item, $cart_item_key)
{
    $tailwind_classes = 'size-full object-cover';

    $thumbnail = str_replace('class="', 'class="' . esc_attr($tailwind_classes) . ' ', $thumbnail);

    return $thumbnail;
}
